---
- name: Get secret from HashiCorp Vault and connect to Proxmox
  hosts: localhost     
  tasks:
    - name: Read secret from Vault
      community.hashi_vault.vault_read:
        url: "{{ vault_url }}"  # URL Vault-сервера
        token: "{{ lookup('env', 'VAULT_TOKEN') }}"  # Берём токен из переменной окружения
        path: "{{ vault_proxmox_path }}"    # Путь к секрету (KV v2)
        validate_certs: false  # Отключить проверку сертификата (небезопасно!)
      register: vault_proxmox
      tags: always

    - name: Add Disk VM
      community.general.proxmox_disk:    
        api_host: "{{ proxmox_ip }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_id }}"
        api_token_secret: "{{ proxmox_secret }}"
        validate_certs: false  # Отключить проверку сертификата Proxmox
        name: "{{ vm_name | default(omit) }}"
        vmid: "{{ vm_vmid | default(omit) }}"
        disk: "{{ item }}"
        cache: writeback
        discard: on
        #backup: false
        #create: forced
        storage: "{{ disk_storage }}"
        size: "{{ disk_size }}"
        state: present
      tags: add_disk
      loop: "{{ disk_type }}"
      when: disk_type is defined

    - name: Resize Disk VM
      community.general.proxmox_disk:    
        api_host: "{{ proxmox_ip }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_id }}"
        api_token_secret: "{{ proxmox_secret }}"
        validate_certs: false  # Отключить проверку сертификата Proxmox
        name: "{{ vm_name | default(omit) }}"
        vmid: "{{ vm_vmid | default(omit) }}"
        disk: "{{ disk_type }}"
        size: "{{ disk_size }}"
        #create: forced
        cache: writeback
        discard: on
        state: resized
      tags: resize_disk 

    - name: Remove Disk VM
      community.general.proxmox_disk:    
        api_host: "{{ proxmox_ip }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_id }}"
        api_token_secret: "{{ proxmox_secret }}"
        validate_certs: false  # Отключить проверку сертификата Proxmox
        name: "{{ vm_name | default(omit) }}"
        vmid: "{{ vm_vmid | default(omit) }}"
        disk: "{{ item }}"
        #create: forced
        state: absent
      tags: remove_disk 
      loop: "{{ disk_type }}"
