---
- name: Get secret from HashiCorp Vault
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read secret from Vault
      community.hashi_vault.vault_read:
        url: "https://10.10.10.22:8200"  # URL Vault-сервера
        token: "{{ lookup('env', 'VAULT_TOKEN') }}"  # Берём токен из переменной окружения
        path: "/proxmox/data/api"    # Путь к секрету (KV v2)
        validate_certs: false  # Отключить проверку сертификата (небезопасно!)
  # ca_cert: "/path/to/ca.pem"  # Если есть свой CA-сертификат
      register: vault_secret

    - name: Display api_user
      ansible.builtin.debug:
        msg: "API User: {{ vault_secret.data.data.data.api_user}}"
      no_log: false  # Показываем значение (если не секретно)
    
