---
- name: Install IPA-client
  hosts: all
  become: true

  roles:
    - { role: install_lib, tags: lib }
    - { role: chronyd, tags: ntp }
    - { role: dns , tags: dns }

  tasks:
    - name: Read secret from Vault
      community.hashi_vault.vault_read:
        url: "{{ vault_url }}" # URL Vault-сервера
        token: "{{ vault_token }}"  # Берём токен из переменной окружения
        path: "{{ vault_ipa_path }}"    # Путь к секрету (KV v2)
        validate_certs: false  # Отключить проверку сертификата 
      register: vault_ipa_reg
      no_log: true
      tags: always

    # - name: Debug vault secret (для отладки)
    #   debug:
    #     var:  "{{ vault_ipa_reg.data.data.data.ipa_login }}"
    #       #- "{{ vault_ipa_reg.data.data.data.ipa_passwd }}"

    - name: Set facts from Vault
      ansible.builtin.set_fact:
        ipa_admin_user: "{{ vault_ipa_reg.data.data.data.ipa_login }}"
        ipa_admin_password: "{{ vault_ipa_reg.data.data.data.ipa_passwd }}"
      no_log: true
      tags: always
     
    - name: Include FreeIPA client role
      import_role: 
        name: freeipa_client 
      tags: ipa
