---
- name: Create Ceph network cluster
  hosts: ip_hosts
  #gather_facts: true
  become: true

  pre_tasks:
    - name: Validate cluster_ip_list variable
      fail:
        msg: "cluster_ip_list must be defined and have the same number of items as hosts"
      when: 
        - cluster_ip_list is not defined or (cluster_ip_list | length) != (groups['ip_hosts'] | length)

    - name: Set cluster_ip for each host based on play order
      set_fact:
        cluster_ip: "{{ cluster_ip_list[groups['ip_hosts'].index(inventory_hostname)] }}"

    - name: Display assigned cluster IP
      debug:
        msg: "Host {{ inventory_hostname }} got cluster IP: {{ cluster_ip }}"
  tasks:

    - name: Import cheph_network role
      import_role: 
        name: ceph_network 
      