---
- name: Create Ceph network cluster
  hosts: all
  gather_facts: true
  become: true

  vars:
    cluster_ip: "{{ cluster_ip | default([]) }}"

  tasks:
    - name: Read secret from Vault
      community.hashi_vault.vault_read:
        url: "{{ vault_url }}"
        token: "{{ lookup('env', 'VAULT_TOKEN') }}"
        path: "{{ vault_proxmox_path }}"
        validate_certs: false
      register: vault_proxmox
      tags: always

    - name: Set facts from Vault
      ansible.builtin.set_fact:
        proxmox_ip: "{{ vault_proxmox.data.data.data.api_host }}"
        proxmox_user: "{{ vault_proxmox.data.data.data.api_user }}"
        proxmox_secret: "{{ vault_proxmox.data.data.data.api_token_proxmox }}"
        proxmox_id: "{{ vault_proxmox.data.data.data.api_token_id }}"
        proxmox_node: "{{ vault_proxmox.data.data.data.node }}"
        vm_passwd: "{{ vault_proxmox.data.data.data.ansible_passwd }}"
        sshkey_ansible: "{{ vault_proxmox.data.data.data.ssh_key_ansible }}"
      no_log: true
      tags: always
     
    - name: Validate cluster_ip variable
      fail:
        msg: "cluster_ip must be defined and have same number of elements as vm_name"
      when: 
        - cluster_ip is not defined or cluster_ip | length == 0
        - cluster_ip | length != vm_name | length
      tags: always

    - name: Create list of VM and IP pairs
      ansible.builtin.set_fact:
        vm_cluster_ips: "{{ vm_name | zip(cluster_ip) | list }}"
      tags: always
     
    - name: Import cheph_network role
      import_role: 
        name: cheph_network 
      vars:
        cluster_ip: "{{ cluster_ip }}"
        vm_cluster_ips: "{{ vm_cluster_ips }}"