---
- name: Configure Ceph network on all VMs
  ansible.builtin.template:
    src: '90-ceph-interface.yaml.j2'
    dest: "/etc/netplan/90-ceph-interface.yaml"
    owner: root
    group: root
    mode: '0644'
  # vars:
  #   cluster_ip: "{{ item }}"
  # loop: "{{ cluster_ip }}"

- name: Apply netplan configuration
  ansible.builtin.command: netplan apply
  become: yes
  become_method: sudo
  register: netplan_result
  failed_when: netplan_result.rc != 0